---
- name: Add users
  ansible.builtin.user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    password: '{{ item.password }}'
    shell: /bin/bash
    createhome: yes
    groups: '{{ item.groups | default(users) }}'
    update_password: "{{ item.update_password | default(update_password) }}"
  with_items: '{{ adduser.users }}'
  when: item.set_password

- name: Reset to default password (P@ssw0rd)
  ansible.builtin.user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    password: "$6$VKqjcNgs4TtBG$qB4rZVnSME1ZVCxd/bWrX2uwKz5VQIYPZA5CEtfuDyIz/BQennnDgyD5vWrai2QpmJU/pqTY2vXqMixinju76."
    shell: /bin/bash
    createhome: yes
    groups: '{{ item.groups | default(users) }}'
    update_password: always
  with_items: '{{ adduser.users }}'
  when: item.reset_password

- name: set authorized key
  authorized_key:
    ansible.builtin.user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    path: /home/{{ item.name }}/.ssh/authorized_keys
    state: present
  with_items: "{{ adduser.users }}"
  
- name: set change password before first login
  command: chage -d 0 {{ item.name }}
  with_items: '{{ adduser.users }}'
  when: item.reset_password

- name: remove user
  ansible.builtin.user:
    name: '{{ item }}'
    state: absent
    remove: yes
  with_items: '{{ rmuser.users }}'
  when: rmuser is defined

- name: lock user
  ansible.builtin.user:
    name: '{{ item }}'
    password_lock: yes
  with_items: '{{ lock.users }}'
  when: lock is defined
...